require 'default.rb'
require 'defaultMappingRegistry.rb'
require 'soap/rpc/driver'

class ExchangeServicePortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = nil

  Methods = [
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/ResolveNames",
      "resolveNames",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "ResolveNames"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "ResolveNamesResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "ResolveNamesResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/ExpandDL",
      "expandDL",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "ExpandDL"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "ExpandDLResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "ExpandDLResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/FindFolder",
      "findFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "FindFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "FindFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "FindFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/FindItem",
      "findItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "FindItem"]],
        #["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        #["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        #["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        #["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "FindItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "FindItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/GetFolder",
      "getFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "GetFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/ConvertId",
      "convertId",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "ConvertId"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "ConvertIdResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "ConvertIdResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/CreateFolder",
      "createFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "CreateFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteFolder",
      "deleteFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "DeleteFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "DeleteFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "DeleteFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateFolder",
      "updateFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "UpdateFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "UpdateFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "UpdateFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/MoveFolder",
      "moveFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "MoveFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "MoveFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "MoveFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/CopyFolder",
      "copyFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CopyFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "CopyFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CopyFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/Subscribe",
      "subscribe",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "Subscribe"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "SubscribeResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SubscribeResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/Unsubscribe",
      "unsubscribe",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "Unsubscribe"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "UnsubscribeResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "UnsubscribeResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/GetEvents",
      "getEvents",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetEvents"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "GetEventsResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetEventsResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderHierarchy",
      "syncFolderHierarchy",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SyncFolderHierarchy"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "SyncFolderHierarchyResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SyncFolderHierarchyResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderItems",
      "syncFolderItems",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SyncFolderItems"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "SyncFolderItemsResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SyncFolderItemsResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/GetItem",
      "getItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetItem"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "GetItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/CreateItem",
      "createItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateItem"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "CreateItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteItem",
      "deleteItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "DeleteItem"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "DeleteItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "DeleteItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateItem",
      "updateItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "UpdateItem"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "UpdateItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "UpdateItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/SendItem",
      "sendItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SendItem"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "SendItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SendItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/MoveItem",
      "moveItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "MoveItem"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "MoveItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "MoveItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/CopyItem",
      "copyItem",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CopyItem"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "CopyItemResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CopyItemResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/CreateAttachment",
      "createAttachment",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateAttachment"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "CreateAttachmentResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateAttachmentResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteAttachment",
      "deleteAttachment",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "DeleteAttachment"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "DeleteAttachmentResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "DeleteAttachmentResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/GetAttachment",
      "getAttachment",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetAttachment"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "GetAttachmentResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetAttachmentResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/CreateManagedFolder",
      "createManagedFolder",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateManagedFolder"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "CreateManagedFolderResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "CreateManagedFolderResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/GetDelegate",
      "getDelegate",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetDelegate"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "GetDelegateResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetDelegateResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/AddDelegate",
      "addDelegate",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "AddDelegate"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "AddDelegateResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "AddDelegateResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/RemoveDelegate",
      "removeDelegate",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "RemoveDelegate"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "RemoveDelegateResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "RemoveDelegateResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateDelegate",
      "updateDelegate",
      [ ["in", "request", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "UpdateDelegate"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["in", "S2SAuth", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        ["in", "MailboxCulture", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "MailboxCulture"]],
        ["in", "RequestVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "RequestServerVersion"]],
        ["out", "UpdateDelegateResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "UpdateDelegateResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserAvailability",
      "getUserAvailability",
      [ ["in", "GetUserAvailabilityRequest", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetUserAvailabilityRequest"]],
        #["in", "SerializedSecurityContext", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "SerializedSecurityContext"]],
        #["in", "ProxyRequestTypeHeader", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ProxyRequestTypeHeader"]],
        #["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["out", "GetUserAvailabilityResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetUserAvailabilityResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserOofSettings",
      "getUserOofSettings",
      [ ["in", "GetUserOofSettingsRequest", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetUserOofSettingsRequest"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["out", "GetUserOofSettingsResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "GetUserOofSettingsResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://schemas.microsoft.com/exchange/services/2006/messages/SetUserOofSettings",
      "setUserOofSettings",
      [ ["in", "SetUserOofSettingsRequest", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SetUserOofSettingsRequest"]],
        ["in", "Impersonation", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ExchangeImpersonation"]],
        ["out", "SetUserOofSettingsResult", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/messages", "SetUserOofSettingsResponse"]],
        ["out", "ServerVersion", ["::SOAP::SOAPElement", "http://schemas.microsoft.com/exchange/services/2006/types", "ServerVersionInfo"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

